### ISSUE TITLE
published ig with version 2.0.4 cannot be used for validation or in a dependen ig

### ISSUE THREAD

**Issue by oliveregger** [IHE/FormatCode#10]
when we want to use the current published formatcode package an error message appears:

oad Package hl7.terminology.r4#2.0.0
2021-04-23 11:14:09.624 [main] INFO  o.h.f.u.npm.BasePackageCacheManager [BasePackageCacheManager.java:80] Failed to resolve package ihe.formatcode.fhir#0.2.4 from server: http://packages.fhir.org
2021-04-23 11:14:09.987 [main] INFO  o.h.f.u.npm.BasePackageCacheManager [BasePackageCacheManager.java:80] Failed to resolve package ihe.formatcode.fhir#0.2.4 from server: http://packages2.fhir.org/packages
2021-04-23 11:14:10.784 [main] INFO  o.h.f.u.npm.BasePackageCacheManager [BasePackageCacheManager.java:80] Failed to resolve package ihe.formatcode.fhir#0.2.x from server: http://packages.fhir.org
2021-04-23 11:14:11.252 [main] INFO  o.h.f.u.npm.BasePackageCacheManager [BasePackageCacheManager.java:80] Failed to resolve package ihe.formatcode.fhir#0.2.x from server: http://packages2.fhir.org/packages
Installing ihe.formatcode.fhir#0.2.4 to the package cache
  Fetching:Publishing Content Failed: Error reading http://profiles.ihe.net/fhir/ihe.formatcode.fhir/0.2.4/package.tgz: Input is not in the .gz format (00:45.0446)
                                                                                 (00:45.0451)
Use -? to get command line help                                                  (00:45.0454)
                                                                                 (00:45.0458)
Stack Dump (for debugging):                                                      (00:45.0463)
java.io.IOException: Error reading http://profiles.ihe.net/fhir/ihe.formatcode.fhir/0.2.4/package.tgz: Input is not in the .gz format
        at org.hl7.fhir.utilities.npm.NpmPackage.readStream(NpmPackage.java:379)
        at org.hl7.fhir.utilities.npm.NpmPackage.fromPackage(NpmPackage.java:370)
        at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.addPackageToCache(File

1. ihe.formatcode.fhir does not appear in the registry , is IHE planning a package feed for their publications?
2. it looks like the package itself is also not published under http://profiles.ihe.net/fhir/ihe.formatcode.fhir/0.2.4/, could this be added?

**Comment by JohnMoehrke** [comment]
@oliveregger is this still a problem?

**Comment by oliveregger** [comment]
@JohnMoehrke no with 1.0.0 this is working, closing this, thanks
